---
- name: ubuntu setup
  hosts: ubuntu
  become: True
  gather_facts: True

  vars_prompt:
    - name: ssh_user
      prompt: enter the allow ssh user name
      private: false

  tasks:
    - name: basic settings
      include_role:
        name: ubuntu_basic

    - name: configure nftables
      include_role:
        name: ubuntu_nftables
