---
- name: ubuntu setup
  hosts: ubuntu
  become: True
  gather_facts: True

  tasks:
    - name: basic settings
      include_role:
        name: ubuntu_basic

    - name: configure nftables
      include_role:
        name: ubuntu_nftables
