---
- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
  listen:
    - systemd-timesyncd reload

- name: system reboot
  reboot:
  listen:
    - system reboot
